// This file has been autogenerated by wlproto from a Wayland XML protocol definition.

#![allow(non_camel_case_types)]
#[allow(unused)]
pub struct zwlr_layer_shell_v1_v5_request_proxy<'a> {
    connection: &'a crate::Connection,
}
#[allow(unused)]
impl<'a> zwlr_layer_shell_v1_v5_request_proxy<'a> {
    pub fn new(connection: &'a crate::Connection) -> Self {
        Self { connection }
    }
    pub async fn send_get_layer_surface(
        &self,
        __object_id: crate::ObjectId,
        id: crate::NewObjectId,
        surface: ::std::option::Option<crate::ObjectId>,
        output: ::std::option::Option<crate::ObjectId>,
        layer: u32,
        namespace: &str,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 0);
        __packet.push_new_id_known_interface(id);
        __packet.push_object(surface);
        __packet.push_object(output);
        __packet.push_uint(layer);
        __packet.push_str(&namespace);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_destroy(&self, __object_id: crate::ObjectId) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 1);
        self.connection.send_packet(&__packet).await
    }
}
pub struct zwlr_layer_shell_v1_v5_request_get_layer_surface_args {
    pub id: crate::NewObjectId,
    pub surface: ::std::option::Option<crate::ObjectId>,
    pub output: ::std::option::Option<crate::ObjectId>,
    pub layer: u32,
    pub namespace: ::std::string::String,
}
impl zwlr_layer_shell_v1_v5_request_get_layer_surface_args {
    pub const OPCODE: u16 = 0;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_shell_v1_v5_request_get_layer_surface_args, crate::Error> {
        let mut __reader = __value.read();
        let id = __reader.read_new_id_known_interface()?;
        let surface = __reader.read_object()?;
        let output = __reader.read_object()?;
        let layer = __reader.read_uint()?;
        let namespace = __reader.read_str()?;
        __reader.finish()?;
        Ok(Self {
            id,
            surface,
            output,
            layer,
            namespace,
        })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_new_id_known_interface(self.id);
        __packet.push_object(self.surface);
        __packet.push_object(self.output);
        __packet.push_uint(self.layer);
        __packet.push_str(&self.namespace);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet>
    for zwlr_layer_shell_v1_v5_request_get_layer_surface_args
{
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_shell_v1_v5_request_get_layer_surface_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_shell_v1_v5_request_get_layer_surface_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_shell_v1_v5_request_destroy_args {}
impl zwlr_layer_shell_v1_v5_request_destroy_args {
    pub const OPCODE: u16 = 1;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_shell_v1_v5_request_destroy_args, crate::Error> {
        let mut __reader = __value.read();
        __reader.finish()?;
        Ok(Self {})
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_shell_v1_v5_request_destroy_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl ::std::convert::TryFrom<(crate::ObjectId, zwlr_layer_shell_v1_v5_request_destroy_args)>
    for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (crate::ObjectId, zwlr_layer_shell_v1_v5_request_destroy_args),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
#[allow(unused)]
pub trait zwlr_layer_surface_v1_v5_event_handler: crate::protocol::EventHandler {
    fn handle_configure(
        &self,
        connection: &crate::Connection,
        packet: crate::Packet,
        serial: u32,
        width: u32,
        height: u32,
    ) -> impl ::std::future::Future<Output = ()> + ::std::marker::Send + ::std::marker::Sync;
    fn handle_closed(
        &self,
        connection: &crate::Connection,
        packet: crate::Packet,
    ) -> impl ::std::future::Future<Output = ()> + ::std::marker::Send + ::std::marker::Sync;
    fn unknown_event(
        &self,
        connection: &crate::Connection,
        packet: crate::Packet,
    ) -> impl ::std::future::Future<Output = ()> + ::std::marker::Send + ::std::marker::Sync {
        let _ = connection;
        let _ = packet;
        ::std::future::ready(())
    }
    fn handle_event(
        &self,
        __connection: &crate::Connection,
        __packet: crate::Packet,
    ) -> impl std::future::Future<Output = ::std::result::Result<(), crate::Error>>
    + ::std::marker::Send
    + ::std::marker::Sync
    where
        Self: Sync,
    {
        async {
            match __packet.opcode() {
                0 => {
                    let mut __packet_reader = __packet.read();
                    let serial = __packet_reader.read_uint()?;
                    let width = __packet_reader.read_uint()?;
                    let height = __packet_reader.read_uint()?;
                    __packet_reader.finish()?;
                    self.handle_configure(__connection, __packet, serial, width, height)
                        .await;
                    Ok(())
                }
                1 => {
                    let mut __packet_reader = __packet.read();
                    __packet_reader.finish()?;
                    self.handle_closed(__connection, __packet).await;
                    Ok(())
                }
                __other => {
                    self.unknown_event(__connection, __packet).await;
                    Ok(())
                }
            }
        }
    }
}
#[allow(unused)]
pub struct zwlr_layer_surface_v1_v5_request_proxy<'a> {
    connection: &'a crate::Connection,
}
#[allow(unused)]
impl<'a> zwlr_layer_surface_v1_v5_request_proxy<'a> {
    pub fn new(connection: &'a crate::Connection) -> Self {
        Self { connection }
    }
    pub async fn send_set_size(
        &self,
        __object_id: crate::ObjectId,
        width: u32,
        height: u32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 0);
        __packet.push_uint(width);
        __packet.push_uint(height);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_set_anchor(
        &self,
        __object_id: crate::ObjectId,
        anchor: u32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 1);
        __packet.push_uint(anchor);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_set_exclusive_zone(
        &self,
        __object_id: crate::ObjectId,
        zone: i32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 2);
        __packet.push_int(zone);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_set_margin(
        &self,
        __object_id: crate::ObjectId,
        top: i32,
        right: i32,
        bottom: i32,
        left: i32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 3);
        __packet.push_int(top);
        __packet.push_int(right);
        __packet.push_int(bottom);
        __packet.push_int(left);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_set_keyboard_interactivity(
        &self,
        __object_id: crate::ObjectId,
        keyboard_interactivity: u32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 4);
        __packet.push_uint(keyboard_interactivity);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_get_popup(
        &self,
        __object_id: crate::ObjectId,
        popup: ::std::option::Option<crate::ObjectId>,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 5);
        __packet.push_object(popup);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_ack_configure(
        &self,
        __object_id: crate::ObjectId,
        serial: u32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 6);
        __packet.push_uint(serial);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_destroy(&self, __object_id: crate::ObjectId) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 7);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_set_layer(
        &self,
        __object_id: crate::ObjectId,
        layer: u32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 8);
        __packet.push_uint(layer);
        self.connection.send_packet(&__packet).await
    }
    pub async fn send_set_exclusive_edge(
        &self,
        __object_id: crate::ObjectId,
        edge: u32,
    ) -> Result<(), crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, 9);
        __packet.push_uint(edge);
        self.connection.send_packet(&__packet).await
    }
}
pub struct zwlr_layer_surface_v1_v5_request_set_size_args {
    pub width: u32,
    pub height: u32,
}
impl zwlr_layer_surface_v1_v5_request_set_size_args {
    pub const OPCODE: u16 = 0;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_set_size_args, crate::Error> {
        let mut __reader = __value.read();
        let width = __reader.read_uint()?;
        let height = __reader.read_uint()?;
        __reader.finish()?;
        Ok(Self { width, height })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_uint(self.width);
        __packet.push_uint(self.height);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_request_set_size_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_set_size_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_set_size_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_set_anchor_args {
    pub anchor: u32,
}
impl zwlr_layer_surface_v1_v5_request_set_anchor_args {
    pub const OPCODE: u16 = 1;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_set_anchor_args, crate::Error> {
        let mut __reader = __value.read();
        let anchor = __reader.read_uint()?;
        __reader.finish()?;
        Ok(Self { anchor })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_uint(self.anchor);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_request_set_anchor_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_set_anchor_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_set_anchor_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_set_exclusive_zone_args {
    pub zone: i32,
}
impl zwlr_layer_surface_v1_v5_request_set_exclusive_zone_args {
    pub const OPCODE: u16 = 2;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_set_exclusive_zone_args, crate::Error> {
        let mut __reader = __value.read();
        let zone = __reader.read_int()?;
        __reader.finish()?;
        Ok(Self { zone })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_int(self.zone);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet>
    for zwlr_layer_surface_v1_v5_request_set_exclusive_zone_args
{
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_set_exclusive_zone_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_set_exclusive_zone_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_set_margin_args {
    pub top: i32,
    pub right: i32,
    pub bottom: i32,
    pub left: i32,
}
impl zwlr_layer_surface_v1_v5_request_set_margin_args {
    pub const OPCODE: u16 = 3;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_set_margin_args, crate::Error> {
        let mut __reader = __value.read();
        let top = __reader.read_int()?;
        let right = __reader.read_int()?;
        let bottom = __reader.read_int()?;
        let left = __reader.read_int()?;
        __reader.finish()?;
        Ok(Self {
            top,
            right,
            bottom,
            left,
        })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_int(self.top);
        __packet.push_int(self.right);
        __packet.push_int(self.bottom);
        __packet.push_int(self.left);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_request_set_margin_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_set_margin_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_set_margin_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_set_keyboard_interactivity_args {
    pub keyboard_interactivity: u32,
}
impl zwlr_layer_surface_v1_v5_request_set_keyboard_interactivity_args {
    pub const OPCODE: u16 = 4;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_set_keyboard_interactivity_args, crate::Error>
    {
        let mut __reader = __value.read();
        let keyboard_interactivity = __reader.read_uint()?;
        __reader.finish()?;
        Ok(Self {
            keyboard_interactivity,
        })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_uint(self.keyboard_interactivity);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet>
    for zwlr_layer_surface_v1_v5_request_set_keyboard_interactivity_args
{
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_set_keyboard_interactivity_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_set_keyboard_interactivity_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_get_popup_args {
    pub popup: ::std::option::Option<crate::ObjectId>,
}
impl zwlr_layer_surface_v1_v5_request_get_popup_args {
    pub const OPCODE: u16 = 5;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_get_popup_args, crate::Error> {
        let mut __reader = __value.read();
        let popup = __reader.read_object()?;
        __reader.finish()?;
        Ok(Self { popup })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_object(self.popup);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_request_get_popup_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_get_popup_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_get_popup_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_ack_configure_args {
    pub serial: u32,
}
impl zwlr_layer_surface_v1_v5_request_ack_configure_args {
    pub const OPCODE: u16 = 6;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_ack_configure_args, crate::Error> {
        let mut __reader = __value.read();
        let serial = __reader.read_uint()?;
        __reader.finish()?;
        Ok(Self { serial })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_uint(self.serial);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet>
    for zwlr_layer_surface_v1_v5_request_ack_configure_args
{
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_ack_configure_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_ack_configure_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_destroy_args {}
impl zwlr_layer_surface_v1_v5_request_destroy_args {
    pub const OPCODE: u16 = 7;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_destroy_args, crate::Error> {
        let mut __reader = __value.read();
        __reader.finish()?;
        Ok(Self {})
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_request_destroy_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_destroy_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_destroy_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_set_layer_args {
    pub layer: u32,
}
impl zwlr_layer_surface_v1_v5_request_set_layer_args {
    pub const OPCODE: u16 = 8;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_set_layer_args, crate::Error> {
        let mut __reader = __value.read();
        let layer = __reader.read_uint()?;
        __reader.finish()?;
        Ok(Self { layer })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_uint(self.layer);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_request_set_layer_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_set_layer_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_set_layer_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_request_set_exclusive_edge_args {
    pub edge: u32,
}
impl zwlr_layer_surface_v1_v5_request_set_exclusive_edge_args {
    pub const OPCODE: u16 = 9;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_request_set_exclusive_edge_args, crate::Error> {
        let mut __reader = __value.read();
        let edge = __reader.read_uint()?;
        __reader.finish()?;
        Ok(Self { edge })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_uint(self.edge);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet>
    for zwlr_layer_surface_v1_v5_request_set_exclusive_edge_args
{
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_request_set_exclusive_edge_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_request_set_exclusive_edge_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_event_configure_args {
    pub serial: u32,
    pub width: u32,
    pub height: u32,
}
impl zwlr_layer_surface_v1_v5_event_configure_args {
    pub const OPCODE: u16 = 0;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_event_configure_args, crate::Error> {
        let mut __reader = __value.read();
        let serial = __reader.read_uint()?;
        let width = __reader.read_uint()?;
        let height = __reader.read_uint()?;
        __reader.finish()?;
        Ok(Self {
            serial,
            width,
            height,
        })
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        __packet.push_uint(self.serial);
        __packet.push_uint(self.width);
        __packet.push_uint(self.height);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_event_configure_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl
    ::std::convert::TryFrom<(
        crate::ObjectId,
        zwlr_layer_surface_v1_v5_event_configure_args,
    )> for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (
            crate::ObjectId,
            zwlr_layer_surface_v1_v5_event_configure_args,
        ),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
pub struct zwlr_layer_surface_v1_v5_event_closed_args {}
impl zwlr_layer_surface_v1_v5_event_closed_args {
    pub const OPCODE: u16 = 1;
    pub fn try_from_packet(
        __value: &crate::Packet,
    ) -> Result<zwlr_layer_surface_v1_v5_event_closed_args, crate::Error> {
        let mut __reader = __value.read();
        __reader.finish()?;
        Ok(Self {})
    }
    pub fn try_into_packet(
        &self,
        __object_id: crate::ObjectId,
    ) -> Result<crate::Packet, crate::Error> {
        let mut __packet = crate::Packet::new(__object_id, Self::OPCODE);
        Ok(__packet)
    }
}
impl ::std::convert::TryFrom<crate::Packet> for zwlr_layer_surface_v1_v5_event_closed_args {
    type Error = crate::Error;
    fn try_from(__value: crate::Packet) -> Result<Self, Self::Error> {
        Self::try_from_packet(&__value)
    }
}
impl ::std::convert::TryFrom<(crate::ObjectId, zwlr_layer_surface_v1_v5_event_closed_args)>
    for crate::Packet
{
    type Error = crate::Error;
    fn try_from(
        __value: (crate::ObjectId, zwlr_layer_surface_v1_v5_event_closed_args),
    ) -> Result<Self, Self::Error> {
        let (__object_id, __structure) = __value;
        __structure.try_into_packet(__object_id)
    }
}
